In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn

In [2]:
!tree data/aclImdb

폴더 PATH의 목록입니다.
볼륨 일련 번호가 000000C1 0639:BF7F입니다.
C:\USERS\RKSLA\DOCUMENTS\PYTHON\BASIC\ML\PPB\DATA\ACLIMDB
├─test
│  ├─neg
│  └─pos
└─train
    ├─neg
    ├─pos
    └─unsup


In [3]:
from sklearn.datasets import load_files

reviews_train = load_files("data/aclImdb/train/")
text_train, y_train = reviews_train.data, reviews_train.target

print("TYPEOF text_train: ", type(text_train))
print("SIZEOF text_train: ", len(text_train))
print("text_train[6]: \n ", text_train[6])

TYPEOF text_train:  <class 'list'>
SIZEOF text_train:  75000
text_train[6]: 
  b'Gloomy Sunday - Ein Lied von Liebe und Tod directed by Rolf Sch\xc3\xbcbel in 1999 is a romantic, absorbing, beautiful, and heartbreaking movie. It started like Jules and Jim; it ended as one of Agatha Christie\'s books, and in between it said something about love, friendship, devotion, jealousy, war, Holocaust, dignity, and betrayal, and it did better than The Black Book which is much more popular. It is not perfect, and it made me, a cynic, wonder in the end on the complexity of the relationships and sensational revelations, and who is who to whom but the movie simply overwhelmed me. Perfect or not, it is unforgettable. All four actors as the parts of the tragic not even a triangle but a rectangle were terrific. I do believe that three men could fell deeply for one girl as beautiful and dignified as Ilona in a star-making performance by young Hungarian actress Erica Marozs\xc3\xa1n and who would not? The

In [4]:
text_train = [doc.replace(b"<br />", b"") for doc in text_train]

In [5]:
print("클래스별 샘플 수 (TRAIN): ", np.bincount(y_train))

클래스별 샘플 수 (TRAIN):  [12500 12500 50000]


In [6]:
reviews_test = load_files("data/aclImdb/test/")
text_test, y_test = reviews_test.data, reviews_test.target

print("테스트 데이터의 문서 수: ", len(text_test))
print("클래스별 샘플 수 (TEST): ")

테스트 데이터의 문서 수:  25000
클래스별 샘플 수 (TEST): 


In [7]:
text_test = [doc.replace(b"<br />", b"") for doc in text_test]

In [8]:
bards_words = [
    "the fool doth think he is wise, ", 
    "but the wise man knows himself to be a fool"
]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
vect.fit(bards_words)

CountVectorizer()

In [10]:
print("어휘 사전의 크기: ", len(vect.vocabulary_))
print("어휘 사전의 내용: \n", vect.vocabulary_)

어휘 사전의 크기:  13
어휘 사전의 내용: 
 {'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [11]:
bag_of_words = vect.transform(bards_words)
print("BOW: ", repr(bag_of_words))

BOW:  <2x13 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>


In [12]:
print("BOW TO NDARRAY: \n", bag_of_words.toarray())

BOW TO NDARRAY: 
 [[0 0 1 1 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 0 1 0 1 1 1 0 1 1]]


In [13]:
wrds = pd.Series(bards_words[0].split(" ")[ : -1])
wrds

0      the
1     fool
2     doth
3    think
4       he
5       is
6    wise,
dtype: object

In [14]:
wrds[6] = wrds[6][ : -1]
wrds

0      the
1     fool
2     doth
3    think
4       he
5       is
6     wise
dtype: object

In [15]:
print(wrds.sort_values().to_list())
print(bag_of_words.toarray()[0])
print(vect.vocabulary_)

['doth', 'fool', 'he', 'is', 'the', 'think', 'wise']
[0 0 1 1 1 0 1 0 0 1 1 0 1]
{'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [16]:
kor_wrds = ["안녕하세요 저는 트위치에서 방송을 하고 있는 스트리머"]

kv = CountVectorizer()
kv.fit(kor_wrds)

CountVectorizer()

In [17]:
print("어휘 사전의 크기: ", len(kv.vocabulary_))
print("어휘 사전의 내용: \n", kv.vocabulary_)

어휘 사전의 크기:  7
어휘 사전의 내용: 
 {'안녕하세요': 2, '저는': 4, '트위치에서': 5, '방송을': 0, '하고': 6, '있는': 3, '스트리머': 1}


In [18]:
kr_bows = vect.transform(kor_wrds)
print("KR_BOW: ", repr(kr_bows))

KR_BOW:  <1x13 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>


In [19]:
print("KR_BOW TO NDARRAY: \n", kr_bows.toarray())

KR_BOW TO NDARRAY: 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [20]:
vect = CountVectorizer().fit(text_train)
X_train = vect.transform(text_train)
print("X_train: \n", repr(X_train))

X_train: 
 <75000x127229 sparse matrix of type '<class 'numpy.int64'>'
	with 10315468 stored elements in Compressed Sparse Row format>


In [21]:
feature_names = vect.get_feature_names_out()

print("특성 개수: ", len(feature_names))
print("특성 [0 : 20]: ", feature_names[ : 20])
print("특성 [20010 : 20030]: ", feature_names[20010 : 20030])
print("특성 [ : : 2000]: ", feature_names[ : : 2000])

특성 개수:  127229
특성 [0 : 20]:  ['00' '000' '0000' '0000000000000000000000000000000001' '0000000000001'
 '000000001' '000000003' '00000001' '000001745' '00001' '0001' '00015'
 '0002' '0007' '00083' '000ft' '000s' '000th' '001' '002']
특성 [20010 : 20030]:  ['cetait' 'cetera' 'cetin' 'cetmes' 'cetnik' 'cetniks' 'ceusescu' 'ceuta'
 'ceylon' 'ceylonese' 'ceylons' 'cezanne' 'cezary' 'cezmi' 'cf' 'cfdc'
 'cfm' 'cfto' 'cg' 'cga']
특성 [ : : 2000]:  ['00' '9out' 'ages' 'andress' 'aryeman' 'baio' 'bellah' 'bloodstain'
 'briers' 'calm' 'cessation' 'circenses' 'complementing' 'countedsix'
 'dahan' 'dench' 'discourages' 'dreamkeeeper' 'elderly' 'esposito' 'fang'
 'flaquer' 'frizzyhead' 'gerry' 'grandness' 'halycon' 'hesitated'
 'hubiriffic' 'incongruence' 'ireperable' 'journal' 'kindsa' 'landingham'
 'limply' 'maaaybbbeee' 'marthe' 'mephestophelion' 'modem' 'mushing'
 'nigger' 'oghris' 'oxbridge' 'pensamentos' 'pleaaaaaaaase' 'prettified'
 'quantify' 'recommendation' 'retrieving' 'rp' 'scam' 'sequiter' 

#### 특성 추출 개선 전 rough data 그대로 썼을 때의 결과

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

scores = cross_val_score(LogisticRegression(max_iter=1000), X_train, y_train, n_jobs=-1)
print("MEAN(CROSS_VAL): {:.2f}".format(np.mean(scores)))

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [10**x for x in range(-3, 2)]}

grid = GridSearchCV(LogisticRegression(max_iter=5000), param_grid, n_jobs=-1)
grid.fit(X_train, y_train)
print("BEST CROSS VAL SCORE: {:.2f}".format(grid.best_score_))
print("BEST PARAMS: ", grid.best_params_)

In [ ]:
X_test = vect.transform(text_test)
print("TEST_SCORE: {:.2f}".format(grid.score(X_test, y_test)))

#### 특성 추출

In [ ]:
vect = CountVectorizer(min_df=5).fit(text_train)
X_train = vect.transform(text_train)

print("min_df로 제한한 X_train: ", repr(X_train))

In [ ]:
feature_names = vect.get_feature_names_out()

print("FEATURE [ : 50] \n", feature_names[ : 50])
print("20010 ~ 20030 \n", feature_names[20010 : 20030])
print("[ : : 700] \n", feature_names[ : : 700])

In [ ]:
grid = GridSearchCV(LogisticRegression(max_iter=5000), param_grid, n_jobs=-1)
grid.fit(X_train, y_train)
print("BEST CROSS VAL SCORE: {:.2f}".format(grid.best_score_))

# 불용어

In [ ]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

print("SIZEOF STOPWORDS: ", len(ENGLISH_STOP_WORDS))
print(list(ENGLISH_STOP_WORDS)[ : : 10])

In [ ]:
vect = CountVectorizer(min_df=5, stop_word="english").fit(text_train)
X_train = vect.transform(text_train)
print(repr(X_train))

In [ ]:
grid = GridSearchCV(LogisiticRegression(max_iter=5000), param_grid, n_jobs=-1)
grid.fit(X_train, y_train)
print("BEST CROSS VAL SCORE: {:.2f}".format(grid.best_score_))

# tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import make_pipeline

pipe = make_pipeline(TfidfVectorizer(min_df=5), LogisticRegression(max_iter=5000))
param_grid = {'logisticregression__C': [10**x for x in range(-3, 3)]}

grid = GridSearchCV(pipe, param_grid, n_jobs=-1)
grid.fit(text_train, y_train)
print("BEST CROSS VAL SCORE: {:.2f}".format(grid.best_score_))

In [ ]:
vectorizer = grid.best_estimator_.named_steps['tfidfvectorizer']

X_train = vectorizer.transform(text_train)
max_value = X_train.max(axis=0).toarray().ravel()
sorted_by_tfidf = max_value.argsort()
feature_names = np.array(vectorizer.get_feature_names_out())

print("LOW-tfidf FEATURES: \n", feature_naems[sorted_by_tfidf[ : 20]])
print("HIGH-tfidf FEATURES: \n", feature_naems[sorted_by_tfidf[-20 : ]])

In [ ]:
sorted_by_idf = np.argsort(vectorizer.idf_)
print("LOWEST-idf FEATURES: \n", feature_names[sorted_by_idf[ : 100]]

In [ ]:
mglearn.tools.visualize_coefficients(
    grid.best_estimator_.named_steps['logisticregression'].coef_[0],
    feature_names, n_top_features=40
)

In [ ]:
print('bards_words: \n', bards_words)

In [ ]:
cv = CounterVectrizer(ngram_range=(1, 1)).fit(bards_words)
print("어휘 사전 크기: ", len(cv.vocabulary_))
print(cv.get_features_names_out())

In [ ]:
cv = CounterVectrizer(ngram_range=(2, 2)).fit(bards_words)
print("어휘 사전 크기: ", len(cv.vocabulary_))
print(cv.get_features_names_out())

In [ ]:
cv = CounterVectrizer(ngram_range=(1, 3)).fit(bards_words)
print("어휘 사전 크기: ", len(cv.vocabulary_))
print(cv.get_features_names_out())

In [ ]:
pipe = make_pipeline(TfidfVectorizer(min_df=5), LogisticRegression(max_iter=5000))

param_grid = {
    'logisticregression__C': [10**x for x in range(-3, 3)],
    'tfidfVectorizer__ngram_range': [(1, 1), (1, 2), (1, 3)]
}

grid = GridSearchCV(pipe, param_grid, n_jobs=-1)
grid.fit(text_train, y_train)

print("BEST CV SCORE: {:.2f}".format(grid.best_score_))
print("BEST PARAMS: ", grid.best_params_)

In [ ]:
scores = grid.cv_results_['mean_test_score'].reshape(-1, 3).T

heatmap = mglearn.tools.heatmap(
    scores,
    xlabel='C', ylabel='ngram_range',
    xticklabels=param_grid['logisticregression__C'], yticklabels=param_grid['tfidfvectorizer__ngram_range']
    cmap='viridis',
    fmt="%.3f",
)

plt.colorbar(heatmap)
plt.show()

In [ ]:
vect = grid.best_estimator_.named_steps['tfidfvectorizer']
feature_naes = np.array(vect.get_feature_names_out())
coef = grid.best_estimator_.naemd_steps['logistigregression'].coef_
mgelarn.tools.visualize_coefficients(coef[0], feature_names, n_top_features=40)

In [ ]:
mask = np.array([len(feature.split(" ")) for feature in feature_names]) == 3

mglearn.tools.visualize_coefficients(coef.ravel()[mask], feature_names[mask], n_top_features=40)

In [ ]:
import spacy
import nltk

nltk.__version__
spacy.__version__

In [ ]:
en_nlp=  spacy.load('en_core_web_sm')
stemmer = nltk.stem.PorterStemmer()

def compare_normalization(doc):
    doc_spacy = en_nlp(doc)
    print("표제어: ")
    print([token.lenna_ for token in doc_spacy])
    print("어간: ")
    print([stemmer.stem(token.norm_.lower()) for token in doc_spacy])

In [ ]:
compare_normalization(
    u"Our meeting today was worse than yesterday, "
    "I'm scared of meeting the clients tomorrow"
)